name: "user_srv"

server:
  host: "127.0.0.1"
  port: "8088"

mysql:
  host: "127.0.0.1"
  port: "8888"
  username: "shijiu"
  password: "Qq1633841065"
  schema: "talkon_user_srv"

logger:
  level: "debug"
  development: "true"
  Encoding: "console"
  EncoderConfig: "dev"
  OutputPaths: "stderr"
