FROM golang:1.20 AS budilder

ENV GORPOXY=https://goproxy.cn,direct
ENV GO111MODULE=on
ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOARCH=amd64


COPY . .
WORKDIR ./user_srv
RUN go build -o usersrv .

FROM scratch AS deployer
COPY --from=budilder /user_srv/usersrv /
COPY --from=budilder /user_srv/conf ./conf
# 声明当前容器中服务的端口
EXPOSE 8088
CMD ["usersrv"]
