FROM golang:1.20 AS budilder

ENV GORPOXY=https://goproxy.cn,direct
    GO111MODULE=on
    CGO_ENABLED=0
    GOOS=linux
    GOARCH=amd64


COPY ./user_srv .
WORKDIR ./user_srv
RUN go mod download
RUN go build -o usersrv .

FROM scratch AS deployer
COPY --from=budilder /user_srv/usersrv /
COPY --from=budilder /user_srv/conf ./conf
# 声明当前容器中服务的端口
EXPOSE 8088
CMD ["usersrv"]
